Repository saleshandy/icons, pull requests merged in 2024-11, with the labels that each got.

#22 feat: added advanced filter icon
  assets/advanced-filter.svg
Labels: enhancement, ready to merge

#23 feat: added external mail icon
  assets/external-email.svg
Labels: enhancement, ready to merge

#24 added trulyinbox asset added
  assets/trulyinbox.svg
Labels: ready to merge

#25 main | add-email-block-icon
  assets/email-block.svg
Labels: ready to review
